name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [master]
    types: [completed]

jobs:
  upload-amaranth-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workdir: "./themes/amaranth"
            projectName: Amaranth

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
        working-directory: ${{ matrix.workdir }}
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          working-directory: ${{ matrix.workdir }}
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          flags: unittests
          name: ${{ matrix.projectName }}
          path_to_write_report: ./coverage/codecov_report.txt

  upload-advanced-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workdir: "./themes/advanced"
            projectName: Advanced

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
        working-directory: ${{ matrix.workdir }}
      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: themes/advanced
          path-to-lcov: themes/advanced/coverage/lcov.info
